# Generated by Django 4.2.1 on 2023-05-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunch_decider', '0003_alter_vote_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
